services:
  - type: web
    name: telegram-bot
    runtime: python312
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sjs.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
